[rknn]
target = "rk3588"

[rknn.model.fuse]
path = "models/fuse.rknn"

[rknn.model.dehaze]
path = "models/dehaze.rknn"

[rknn.model.yolo]
conf_threshold = 0.6
path = "models/yolo11n.rknn"

[thread]
maxsize = 120
max_workers = 20

[thread.dehaze]
max_workers = 2

[thread.fuse]
max_workers = 2

[thread.detect]
max_workers = 2

[output]
H = 480
W = 854
IMG_SIZE = 640

[output.path.video]
infrared = "videos/smoked_rgb25.mp4"
thermal = "videos/smoked_tr30.mp4"
